# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: UseNode@1
  inputs:

trigger:
  - master
pool:
  vmImage: 'vs2017-win2016'
steps:
  - script: python build.py --test
  - script: python build.py --web --test


